/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1alpha2 "github.com/kcp-dev/sdk/apis/apis/v1alpha2"
	apisv1alpha2 "github.com/kcp-dev/sdk/client/applyconfiguration/apis/v1alpha2"
	typedapisv1alpha2 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/apis/v1alpha2"
)

// fakeFilteredAPIExportEndpointSlices implements FilteredAPIExportEndpointSliceInterface
type fakeFilteredAPIExportEndpointSlices struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.FilteredAPIExportEndpointSlice, *v1alpha2.FilteredAPIExportEndpointSliceList, *apisv1alpha2.FilteredAPIExportEndpointSliceApplyConfiguration]
	Fake *FakeApisV1alpha2
}

func newFakeFilteredAPIExportEndpointSlices(fake *FakeApisV1alpha2) typedapisv1alpha2.FilteredAPIExportEndpointSliceInterface {
	return &fakeFilteredAPIExportEndpointSlices{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.FilteredAPIExportEndpointSlice, *v1alpha2.FilteredAPIExportEndpointSliceList, *apisv1alpha2.FilteredAPIExportEndpointSliceApplyConfiguration](
			fake.Fake,
			"",
			v1alpha2.SchemeGroupVersion.WithResource("filteredapiexportendpointslices"),
			v1alpha2.SchemeGroupVersion.WithKind("FilteredAPIExportEndpointSlice"),
			func() *v1alpha2.FilteredAPIExportEndpointSlice { return &v1alpha2.FilteredAPIExportEndpointSlice{} },
			func() *v1alpha2.FilteredAPIExportEndpointSliceList {
				return &v1alpha2.FilteredAPIExportEndpointSliceList{}
			},
			func(dst, src *v1alpha2.FilteredAPIExportEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.FilteredAPIExportEndpointSliceList) []*v1alpha2.FilteredAPIExportEndpointSlice {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.FilteredAPIExportEndpointSliceList, items []*v1alpha2.FilteredAPIExportEndpointSlice) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
