/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
	apisv1alpha2 "github.com/kcp-dev/sdk/apis/apis/v1alpha2"
	kcpv1alpha2 "github.com/kcp-dev/sdk/client/applyconfiguration/apis/v1alpha2"
	typedkcpapisv1alpha2 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/apis/v1alpha2"
	typedapisv1alpha2 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/apis/v1alpha2"
)

// filteredAPIExportEndpointSliceClusterClient implements FilteredAPIExportEndpointSliceClusterInterface
type filteredAPIExportEndpointSliceClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*apisv1alpha2.FilteredAPIExportEndpointSlice, *apisv1alpha2.FilteredAPIExportEndpointSliceList]
	Fake *kcptesting.Fake
}

func newFakeFilteredAPIExportEndpointSliceClusterClient(fake *ApisV1alpha2ClusterClient) typedkcpapisv1alpha2.FilteredAPIExportEndpointSliceClusterInterface {
	return &filteredAPIExportEndpointSliceClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*apisv1alpha2.FilteredAPIExportEndpointSlice, *apisv1alpha2.FilteredAPIExportEndpointSliceList](
			fake.Fake,
			apisv1alpha2.SchemeGroupVersion.WithResource("filteredapiexportendpointslices"),
			apisv1alpha2.SchemeGroupVersion.WithKind("FilteredAPIExportEndpointSlice"),
			func() *apisv1alpha2.FilteredAPIExportEndpointSlice {
				return &apisv1alpha2.FilteredAPIExportEndpointSlice{}
			},
			func() *apisv1alpha2.FilteredAPIExportEndpointSliceList {
				return &apisv1alpha2.FilteredAPIExportEndpointSliceList{}
			},
			func(dst, src *apisv1alpha2.FilteredAPIExportEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *apisv1alpha2.FilteredAPIExportEndpointSliceList) []*apisv1alpha2.FilteredAPIExportEndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *apisv1alpha2.FilteredAPIExportEndpointSliceList, items []*apisv1alpha2.FilteredAPIExportEndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *filteredAPIExportEndpointSliceClusterClient) Cluster(cluster logicalcluster.Path) typedapisv1alpha2.FilteredAPIExportEndpointSliceInterface {
	return newFakeFilteredAPIExportEndpointSliceClient(c.Fake, cluster)
}

// filteredAPIExportEndpointSliceScopedClient implements FilteredAPIExportEndpointSliceInterface
type filteredAPIExportEndpointSliceScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*apisv1alpha2.FilteredAPIExportEndpointSlice, *apisv1alpha2.FilteredAPIExportEndpointSliceList, *kcpv1alpha2.FilteredAPIExportEndpointSliceApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeFilteredAPIExportEndpointSliceClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedapisv1alpha2.FilteredAPIExportEndpointSliceInterface {
	return &filteredAPIExportEndpointSliceScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*apisv1alpha2.FilteredAPIExportEndpointSlice, *apisv1alpha2.FilteredAPIExportEndpointSliceList, *kcpv1alpha2.FilteredAPIExportEndpointSliceApplyConfiguration](
			fake,
			clusterPath,
			"",
			apisv1alpha2.SchemeGroupVersion.WithResource("filteredapiexportendpointslices"),
			apisv1alpha2.SchemeGroupVersion.WithKind("FilteredAPIExportEndpointSlice"),
			func() *apisv1alpha2.FilteredAPIExportEndpointSlice {
				return &apisv1alpha2.FilteredAPIExportEndpointSlice{}
			},
			func() *apisv1alpha2.FilteredAPIExportEndpointSliceList {
				return &apisv1alpha2.FilteredAPIExportEndpointSliceList{}
			},
			func(dst, src *apisv1alpha2.FilteredAPIExportEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *apisv1alpha2.FilteredAPIExportEndpointSliceList) []*apisv1alpha2.FilteredAPIExportEndpointSlice {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *apisv1alpha2.FilteredAPIExportEndpointSliceList, items []*apisv1alpha2.FilteredAPIExportEndpointSlice) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
