/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	logicalcluster "github.com/kcp-dev/logicalcluster/v3"
	kcpapisv1alpha2 "github.com/kcp-dev/sdk/apis/apis/v1alpha2"
	kcpversioned "github.com/kcp-dev/sdk/client/clientset/versioned"
	kcpcluster "github.com/kcp-dev/sdk/client/clientset/versioned/cluster"
	kcpinternalinterfaces "github.com/kcp-dev/sdk/client/informers/externalversions/internalinterfaces"
	kcpv1alpha2 "github.com/kcp-dev/sdk/client/listers/apis/v1alpha2"
)

// FilteredAPIExportEndpointSliceClusterInformer provides access to a shared informer and lister for
// FilteredAPIExportEndpointSlices.
type FilteredAPIExportEndpointSliceClusterInformer interface {
	Cluster(logicalcluster.Name) FilteredAPIExportEndpointSliceInformer
	ClusterWithContext(context.Context, logicalcluster.Name) FilteredAPIExportEndpointSliceInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kcpv1alpha2.FilteredAPIExportEndpointSliceClusterLister
}

type filteredAPIExportEndpointSliceClusterInformer struct {
	factory          kcpinternalinterfaces.SharedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// NewFilteredAPIExportEndpointSliceClusterInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportEndpointSliceClusterInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFilteredAPIExportEndpointSliceClusterInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha2().FilteredAPIExportEndpointSlices().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha2().FilteredAPIExportEndpointSlices().Watch(context.Background(), options)
			},
		},
		&kcpapisv1alpha2.FilteredAPIExportEndpointSlice{},
		resyncPeriod,
		indexers,
	)
}

func (i *filteredAPIExportEndpointSliceClusterInformer) defaultInformer(client kcpcluster.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,
	}, i.tweakListOptions)
}

func (i *filteredAPIExportEndpointSliceClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return i.factory.InformerFor(&kcpapisv1alpha2.FilteredAPIExportEndpointSlice{}, i.defaultInformer)
}

func (i *filteredAPIExportEndpointSliceClusterInformer) Lister() kcpv1alpha2.FilteredAPIExportEndpointSliceClusterLister {
	return kcpv1alpha2.NewFilteredAPIExportEndpointSliceClusterLister(i.Informer().GetIndexer())
}

func (i *filteredAPIExportEndpointSliceClusterInformer) Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceInformer {
	return &filteredAPIExportEndpointSliceInformer{
		informer: i.Informer().Cluster(clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

func (i *filteredAPIExportEndpointSliceClusterInformer) ClusterWithContext(ctx context.Context, clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceInformer {
	return &filteredAPIExportEndpointSliceInformer{
		informer: i.Informer().ClusterWithContext(ctx, clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

type filteredAPIExportEndpointSliceInformer struct {
	informer cache.SharedIndexInformer
	lister   kcpv1alpha2.FilteredAPIExportEndpointSliceLister
}

func (i *filteredAPIExportEndpointSliceInformer) Informer() cache.SharedIndexInformer {
	return i.informer
}

func (i *filteredAPIExportEndpointSliceInformer) Lister() kcpv1alpha2.FilteredAPIExportEndpointSliceLister {
	return i.lister
}

// FilteredAPIExportEndpointSliceInformer provides access to a shared informer and lister for
// FilteredAPIExportEndpointSlices.
type FilteredAPIExportEndpointSliceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kcpv1alpha2.FilteredAPIExportEndpointSliceLister
}

type filteredAPIExportEndpointSliceScopedInformer struct {
	factory          kcpinternalinterfaces.SharedScopedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// NewFilteredAPIExportEndpointSliceInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportEndpointSliceInformer(client kcpversioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFilteredAPIExportEndpointSliceInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFilteredAPIExportEndpointSliceInformer(client kcpversioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha2().FilteredAPIExportEndpointSlices().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha2().FilteredAPIExportEndpointSlices().Watch(context.Background(), options)
			},
		},
		&kcpapisv1alpha2.FilteredAPIExportEndpointSlice{},
		resyncPeriod,
		indexers,
	)
}

func (i *filteredAPIExportEndpointSliceScopedInformer) Informer() cache.SharedIndexInformer {
	return i.factory.InformerFor(&kcpapisv1alpha2.FilteredAPIExportEndpointSlice{}, i.defaultInformer)
}

func (i *filteredAPIExportEndpointSliceScopedInformer) Lister() kcpv1alpha2.FilteredAPIExportEndpointSliceLister {
	return kcpv1alpha2.NewFilteredAPIExportEndpointSliceLister(i.Informer().GetIndexer())
}

func (i *filteredAPIExportEndpointSliceScopedInformer) defaultInformer(client kcpversioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceInformer(client, resyncPeriod, cache.Indexers{}, i.tweakListOptions)
}
