/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	kcplisters "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/listers"
	"github.com/kcp-dev/logicalcluster/v3"
	kcpv1alpha2 "github.com/kcp-dev/sdk/apis/apis/v1alpha2"
)

// FilteredAPIExportEndpointSliceClusterLister helps list FilteredAPIExportEndpointSlices across all workspaces,
// or scope down to a FilteredAPIExportEndpointSliceLister for one workspace.
// All objects returned here must be treated as read-only.
type FilteredAPIExportEndpointSliceClusterLister interface {
	// List lists all FilteredAPIExportEndpointSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kcpv1alpha2.FilteredAPIExportEndpointSlice, err error)
	// Cluster returns a lister that can list and get FilteredAPIExportEndpointSlices in one workspace.
	Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceLister
	FilteredAPIExportEndpointSliceClusterListerExpansion
}

// filteredAPIExportEndpointSliceClusterLister implements the FilteredAPIExportEndpointSliceClusterLister interface.
type filteredAPIExportEndpointSliceClusterLister struct {
	kcplisters.ResourceClusterIndexer[*kcpv1alpha2.FilteredAPIExportEndpointSlice]
}

var _ FilteredAPIExportEndpointSliceClusterLister = new(filteredAPIExportEndpointSliceClusterLister)

// NewFilteredAPIExportEndpointSliceClusterLister returns a new FilteredAPIExportEndpointSliceClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewFilteredAPIExportEndpointSliceClusterLister(indexer cache.Indexer) FilteredAPIExportEndpointSliceClusterLister {
	return &filteredAPIExportEndpointSliceClusterLister{
		kcplisters.NewCluster[*kcpv1alpha2.FilteredAPIExportEndpointSlice](indexer, kcpv1alpha2.Resource("filteredapiexportendpointslice")),
	}
}

// Cluster scopes the lister to one workspace, allowing users to list and get FilteredAPIExportEndpointSlices.
func (l *filteredAPIExportEndpointSliceClusterLister) Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceLister {
	return &filteredAPIExportEndpointSliceLister{
		l.ResourceClusterIndexer.WithCluster(clusterName),
	}
}

// filteredAPIExportEndpointSliceLister can list all FilteredAPIExportEndpointSlices inside a workspace
// or scope down to a FilteredAPIExportEndpointSliceNamespaceLister for one namespace.
type filteredAPIExportEndpointSliceLister struct {
	kcplisters.ResourceIndexer[*kcpv1alpha2.FilteredAPIExportEndpointSlice]
}

var _ FilteredAPIExportEndpointSliceLister = new(filteredAPIExportEndpointSliceLister)

// FilteredAPIExportEndpointSliceLister can list all FilteredAPIExportEndpointSlices, or get one in particular.
// All objects returned here must be treated as read-only.
type FilteredAPIExportEndpointSliceLister interface {
	// List lists all FilteredAPIExportEndpointSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kcpv1alpha2.FilteredAPIExportEndpointSlice, err error)
	// Get retrieves the FilteredAPIExportEndpointSlice from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kcpv1alpha2.FilteredAPIExportEndpointSlice, error)
	FilteredAPIExportEndpointSliceListerExpansion
}

// NewFilteredAPIExportEndpointSliceLister returns a new FilteredAPIExportEndpointSliceLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewFilteredAPIExportEndpointSliceLister(indexer cache.Indexer) FilteredAPIExportEndpointSliceLister {
	return &filteredAPIExportEndpointSliceLister{
		kcplisters.New[*kcpv1alpha2.FilteredAPIExportEndpointSlice](indexer, kcpv1alpha2.Resource("filteredapiexportendpointslice")),
	}
}

// filteredAPIExportEndpointSliceScopedLister can list all FilteredAPIExportEndpointSlices inside a workspace
// or scope down to a FilteredAPIExportEndpointSliceNamespaceLister.
type filteredAPIExportEndpointSliceScopedLister struct {
	kcplisters.ResourceIndexer[*kcpv1alpha2.FilteredAPIExportEndpointSlice]
}
